spring:
  profiles:
    active: dev

xxl:
  job:
    admin:
      addresses: http://192.168.56.7:7777/xxl-job-admin
    accessToken:

    executor:
      port: 9998
      appname: xxl-job-executor-shuolid
      address:
      ip: 192.168.56.7
      logpath: /usr/xxl-job/logs
      logretentiondays: 15
