spring:
  profiles:
    active: dev

xxl:
  job:
    admin:
      addresses: http://10.0.2.15:7777/xxl-job-admin
    accessToken: ''

    executor:
      port: 9998
      appname: xxl-job-executor-shuolid
      address: ''
      ip: ''
      logpath: ''
      logretentiondays: 15
