spring:
  profiles:
    active: dev

xxl:
  job:
    admin:
      addresses: http://192.168.56.7:9999/xxl-job-admin
    accessToken:

    executor:
      port: 9998
      appname: xxl-job-executor-sample
      address:
      ip:
      logpath:
      logretentiondays: 15