spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: prod

xxl:
  job:
    admin:
      addresses: http://192.168.56.7:7777/xxl-job-admin
    accessToken:

    executor:
      port: 9999
      appname: xxl-job-executor-shuolid
      address:
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

