spring:
  profiles:
    active: dev

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7777/xxl-job-admin
    accessToken:

    executor:
      port: 9998
      appname: xxl-job-executor-shuolid
      address: http://127.0.0.1:9998
      ip: 127.0.0.1
      logpath: /usr/xxl-job/logs
      logretentiondays: 15
