spring:
  profiles:
    active: dev

xxl:
  job:
    admin:
      addresses: http://192.168.56.7:7777/xxl-job-admin
    accessToken:

    executor:
      port:
      appname: xxl-job-executor-shuolid
      address:
      ip:
      logpath:
      logretentiondays: 15

