spring:
  profiles:
    active: dev

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7777/xxl-job-admin
    accessToken:

    executor:
      port: 9999
      appname: xxl-job-executor-shuolid
      address:
      ip:
      logpath:
      logretentiondays: 15

